# Generated by Django 5.2.3 on 2025-07-03 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='members',
            field=models.ManyToManyField(related_name='members_group', to='sharing.users'),
        ),
        migrations.AlterField(
            model_name='resourceusershare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sharing.users'),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
